default:
  image: debian:bookworm-slim

stages:
  - build

build armsom-sige5:
  stage: build
  variables:
    DEBIAN_FRONTEND: noninteractive
    GIT_STRATEGY: fetch
    GIT_DEPTH: "1"
    RKBIN_REPO_URL: "https://github.com/rockchip-linux/rkbin.git"
  before_script:
    - apt update
    - apt install -y bc build-essential
                        crossbuild-essential-arm64
                        device-tree-compiler
                        git
                        python3
                        bison
                        flex
                        python3-setuptools
                        swig
                        python3-dev
                        libssl-dev
                        python3-pyelftools
                        uuid-dev
                        gnutls-dev
                        gawk
  script:
    # download rkbin
    - git clone --depth 1 -b master ${RKBIN_REPO_URL} $CI_PROJECT_DIR/../rkbin

    # prepare PATH
    - export CROSS_COMPILE=aarch64-linux-gnu-
    - export ARCH=arm64

    # Point BL31 and TPL to rkbin, dynamically extract the right ones from Rockchip's official repo
    - export BL31=../rkbin/$(cat $CI_PROJECT_DIR/../rkbin/RKTRUST/RK3576TRUST.ini | gawk 'match($0, /^PATH=(.*bl31.*)/, a) { print a[1] }')
    - export ROCKCHIP_TPL=../rkbin/$(cat $CI_PROJECT_DIR/../rkbin/RKBOOT/RK3576MINIALL.ini | gawk 'match($0, /^FlashData=(.*)/, a) { print a[1] }')

    # build
    - cd $CI_PROJECT_DIR
    - make -j$(nproc) mrproper
    - make sige5-rk3576_defconfig
    - make -j$(nproc)

    # proprietary USB loader
    - cd $CI_PROJECT_DIR/../rkbin && ./tools/boot_merger RKBOOT/RK3576MINIALL.ini && mv *spl_loader*.bin $CI_PROJECT_DIR

  artifacts:
    paths:
      - u-boot-rockchip.bin
      - rk3576_spl_loader_*.bin
