default:
  image: debian:bookworm-slim

stages:
  - build

build armsom-sige5:
  stage: build
  variables:
    DEBIAN_FRONTEND: noninteractive
    GIT_STRATEGY: fetch
    GIT_DEPTH: "1"
    RKBIN_REPO_URL: "https://github.com/rockchip-linux/rkbin.git"
    TFA_REPO_URL: "https://review.trustedfirmware.org/TF-A/trusted-firmware-a.git"
  before_script:
    - apt update
    - apt install -y bc build-essential
                        crossbuild-essential-arm64
                        device-tree-compiler
                        git
                        python3
                        bison
                        flex
                        python3-setuptools
                        swig
                        python3-dev
                        libssl-dev
                        python3-pyelftools
                        uuid-dev
                        gnutls-dev
                        gawk
  script:
    # download rkbin
    - git clone --depth 1 -b master ${RKBIN_REPO_URL} $CI_PROJECT_DIR/../rkbin

    # download TF-A
    - git clone --depth 1 -b master ${TFA_REPO_URL} $CI_PROJECT_DIR/../trusted-firmware-a

    # prepare PATH
    - export CROSS_COMPILE=aarch64-linux-gnu-
    - export ARCH=arm64

    # build TF-A
    - cd $CI_PROJECT_DIR/../trusted-firmware-a
    - make E=0 PLAT=rk3576 bl31

    - cd $CI_PROJECT_DIR

    # Point BL31 to the TF-A we built
    - export BL31=../trusted-firmware-a/build/rk3576/release/bl31/bl31.elf
    # Point TPL to rkbin, dynamically extract the right one from Rockchip's official repo
    - export ROCKCHIP_TPL=../rkbin/$(cat $CI_PROJECT_DIR/../rkbin/RKBOOT/RK3576MINIALL.ini | gawk 'match($0, /^FlashData=(.*)/, a) { print a[1] }')

    # build
    - make -j$(nproc) mrproper
    - make sige5-rk3576_defconfig
    - make -j$(nproc)

    # proprietary USB loader
    - cd $CI_PROJECT_DIR/../rkbin && ./tools/boot_merger RKBOOT/RK3576MINIALL.ini && mv *spl_loader*.bin $CI_PROJECT_DIR

  artifacts:
    paths:
      - u-boot-rockchip.bin
      - rk3576_spl_loader_*.bin
